name: Build and Push to Sakura Cloud Container Registry

on:
  workflow_call:
    inputs:
      registry-name:
        description: 'Sakura Cloud Container Registry name (e.g., your-registry.sakuracr.jp)'
        required: true
        type: string
      image-name:
        description: 'Image name (default: repository name)'
        required: false
        type: string
        default: ''
      context:
        description: 'Build context path'
        required: false
        type: string
        default: '.'
      dockerfile:
        description: 'Path to Dockerfile'
        required: false
        type: string
        default: './Dockerfile'
      runs-on:
        description: 'Runner to use'
        required: false
        type: string
        default: '["ubuntu-latest"]'
      build-args:
        description: 'Build arguments (multiline)'
        required: false
        type: string
        default: ''
    secrets:
      registry-username:
        description: 'Sakura Cloud Container Registry username'
        required: true
      registry-password:
        description: 'Sakura Cloud Container Registry password'
        required: true

jobs:
  build-and-push:
    runs-on: ${{ fromJSON(inputs.runs-on) }}
    
    permissions:
      contents: read
      
    steps:
      - name: Checkout Repository
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@37fe631027851001ddb9b187196cc803df7f5f0e # v4.3.0

      - name: Login to Sakura Cloud Container Registry
        uses: docker/login-action@dbcb813823bdd20940b903addbd779551569679f # v4.6.0
        with:
          registry: ${{ inputs.registry-name }}
          username: ${{ secrets.registry-username }}
          password: ${{ secrets.registry-password }}

      - name: Build and push Docker image
        uses: docker/build-push-action@c3c9e263c25d99ce0380d002d59b67737d91b0dc # v7.4.0
        with:
          context: ${{ inputs.context }}
          file: ${{ inputs.dockerfile }}
          push: true
          tags: ${{ inputs.registry-name }}/${{ inputs.image-name || github.repository }}:${{ github.ref_name }}
          build-args: ${{ inputs.build-args }}
